# Generated by Django 2.2 on 2020-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_names_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='a_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='names',
            name='e_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='names',
            name='g_score',
            field=models.FloatField(default=0),
        ),
    ]
